# Пример конфигурации для модуля ESP-C3-12F
# В стике от @dudanov модуль ESP-12F на базе esp8266 можно заменить на ESP-C3-12F на базе ESP32-C3
# При первоначальной прошивке через UART, GPIO8 (I08) необходимо замкнуть с VCC 
# и очень желательно через резистор номиналом 10 кОм
#
# https://templates.blakadder.com/ESP-C3-12F.html
# https://docs.rs-online.com/0b18/A700000008521004.pdf
esphome:
  name: ac-f1-kitchen
  friendly_name: ac-f1-kitchen
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  # Только на сетевом интерфейсе, вывод  в web консоль
  # UART используется для взаимодействия с кондиционером
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "YOU-KEY-API"

ota:
  - platform: esphome
    password: "YOU-KEY-OTA"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ac-F1-Kitchen Fallback Hotspot"
    password: "YOU-PASSWORD-HOTSTOP-FAIL"

captive_portal:

# Использование внешних компанент
external_components:
  - source: github://Anat0l/hisense_acu2d
    components: [ hisense_acu2d ]
    refresh: 0s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
#  - platform: homeassistant
#    id: kitchen_ac
#    entity_id: sensor.kitchen_ac

# Настройка UART
uart:
#  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 1200

# Передатчик
remote_transmitter:
  id: "acu2d_transmitter"
  pin:
    number: GPIO05
    inverted: False
  carrier_duty_percent: 100%

# Приемник 
# Приемник не нужен
#remote_receiver:
#  id: "debug_receiver"
#  pin:
#    number: GPIO10
#    inverted: True
#    mode:
#      input: true
#      pullup: False
#  tolerance: 55%

climate:
  - platform: hisense_acu2d
    id: hisense_acu2d_climate
    name: "Кондиционер"
    transmitter_id: "acu2d_transmitter"
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step: 1.0
    supported_swing_modes:
      - 'OFF'
      - VERTICAL
      - HORIZONTAL
      - BOTH
#    ifeel_sensor: kitchen_ac
#    ifeel_switch:
#      name: iFeel
#    dimmer_switch:
#      name: Dimmer
