esphome:
  name: esp-hisense-acu2d
  friendly_name: esp_hisense_acu2d

esp8266:
  board: esp01_1m

# Enable logging
logger:
  # Только на сетевом интерфейсе, вывод  в web консоль
  # UART используется для взаимодействия с кондиционером
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "8SK6qK2Gwu+pqwNr60TS0xo2s6rOYlLxvQQGWQILMfE="

ota:
  - platform: esphome
    password: "ef652f7767b6792c96949065ab427f3e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Hisense-Acu2D"
    password: "ZAL3TWOfRaPV"

captive_portal:

web_server:
  port: 80

# Использование внешних компанент
external_components:
  - source: github://Anat0l/hisense_acu2d
    components: [ hisense_acu2d ]
    refresh: 0s

# Настройка UART
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 1200

# Передатчик
remote_transmitter:
  id: "acu2d_transmitter"
  pin: 
    number: GPIO13
    inverted: False
  carrier_duty_percent: 100%

climate:
  - platform: hisense_acu2d
    id: hisense_acu2d_climate
    name: "Кондиционер"
    transmitter_id: "acu2d_transmitter"
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step: 1.0
    supported_swing_modes:
      - 'OFF'
      - VERTICAL
      - HORIZONTAL
      - BOTH
